// apps/api/src/lib/observability/events.ts
// Centralized Event Taxonomy Constants for AutoEOD

export const EventTaxonomy = {
  // Authentication & Session
  AUTH: {
    LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
    LOGIN_FAILED: 'AUTH.LOGIN_FAILED',
    LOGOUT: 'AUTH.LOGOUT',
    TOKEN_REFRESH: 'AUTH.TOKEN_REFRESH',
    TOKEN_REFRESH_FAILED: 'AUTH.TOKEN_REFRESH_FAILED',
    TOKEN_REVOKED: 'AUTH.TOKEN_REVOKED',
    PASSWORD_CHANGED: 'AUTH.PASSWORD_CHANGED',
    SIGNUP_SUCCESS: 'AUTH.SIGNUP_SUCCESS',
    SIGNUP_FAILED: 'AUTH.SIGNUP_FAILED',
    GOOGLE_AUTH_SUCCESS: 'AUTH.GOOGLE_AUTH_SUCCESS',
    GOOGLE_AUTH_FAILED: 'AUTH.GOOGLE_AUTH_FAILED',
    ZOHO_AUTH_SUCCESS: 'AUTH.ZOHO_AUTH_SUCCESS',
    ZOHO_AUTH_FAILED: 'AUTH.ZOHO_AUTH_FAILED',
  },

  // User Lifecycle & Profile
  USER: {
    ACCOUNT_CREATED: 'USER.ACCOUNT_CREATED',
    ACCOUNT_DELETED: 'USER.ACCOUNT_DELETED',
    PROFILE_UPDATED: 'USER.PROFILE_UPDATED',
    SETTINGS_CHANGED: 'USER.SETTINGS_CHANGED',
    EXTENSION_SETTINGS_UPDATED: 'USER.EXTENSION_SETTINGS_UPDATED',
    TIMELINE_SETTINGS_UPDATED: 'USER.TIMELINE_SETTINGS_UPDATED',
    HOLIDAY_ADDED: 'USER.HOLIDAY_ADDED',
    HOLIDAY_REMOVED: 'USER.HOLIDAY_REMOVED',
  },

  // Admin & Governance
  ADMIN: {
    CONFIG_UPDATED: 'ADMIN.CONFIG_UPDATED',
    USER_ROLE_CHANGED: 'ADMIN.USER_ROLE_CHANGED',
    USER_DELETED: 'ADMIN.USER_DELETED',
    TEMPLATE_CREATED: 'ADMIN.TEMPLATE_CREATED',
    TEMPLATE_UPDATED: 'ADMIN.TEMPLATE_UPDATED',
    TEMPLATE_DELETED: 'ADMIN.TEMPLATE_DELETED',
    EXTENSION_RELEASE_BUILT: 'ADMIN.EXTENSION_RELEASE_BUILT',
    EXPORT_REQUESTED: 'ADMIN.EXPORT_REQUESTED',
    RETENTION_UPDATED: 'ADMIN.RETENTION_UPDATED',
    ALERT_CONFIGURED: 'ADMIN.ALERT_CONFIGURED',
    ALERT_DELETED: 'ADMIN.ALERT_DELETED',
    ALERT_TRIGGERED: 'ADMIN.ALERT_TRIGGERED',
    ERROR_RESOLVED: 'ADMIN.ERROR_RESOLVED',
    ERROR_IGNORED: 'ADMIN.ERROR_IGNORED',
    LOG_SETTINGS_UPDATED: 'ADMIN.LOG_SETTINGS_UPDATED',
  },

  // HTTP API Layer
  API: {
    REQUEST_COMPLETED: 'API.REQUEST_COMPLETED',
    REQUEST_FAILED: 'API.REQUEST_FAILED',
    RATE_LIMIT_EXCEEDED: 'API.RATE_LIMIT_EXCEEDED',
  },

  // EOD Reports & Generation
  REPORT: {
    GENERATION_QUEUED: 'REPORT.GENERATION_QUEUED',
    GENERATION_STARTED: 'REPORT.GENERATION_STARTED',
    GENERATED: 'REPORT.GENERATED',
    GENERATION_FAILED: 'REPORT.GENERATION_FAILED',
    VIEWED: 'REPORT.VIEWED',
    UPDATED: 'REPORT.UPDATED',
    EXPORTED: 'REPORT.EXPORTED',
    STATUS_CHANGED: 'REPORT.STATUS_CHANGED',
  },

  // AI Inference & Model Fallbacks
  AI: {
    REQUEST_STARTED: 'AI.REQUEST_STARTED',
    REQUEST_COMPLETED: 'AI.REQUEST_COMPLETED',
    REQUEST_FAILED: 'AI.REQUEST_FAILED',
    FALLBACK_TRIGGERED: 'AI.FALLBACK_TRIGGERED',
    TOKEN_USAGE_LOGGED: 'AI.TOKEN_USAGE_LOGGED',
  },

  // External Integrations (GitHub, OAuth, etc.)
  GITHUB: {
    CONNECTED: 'GITHUB.CONNECTED',
    DISCONNECTED: 'GITHUB.DISCONNECTED',
    SYNC_QUEUED: 'GITHUB.SYNC_QUEUED',
    SYNC_STARTED: 'GITHUB.SYNC_STARTED',
    SYNC_COMPLETED: 'GITHUB.SYNC_COMPLETED',
    SYNC_FAILED: 'GITHUB.SYNC_FAILED',
    RATE_LIMIT_EXCEEDED: 'GITHUB.RATE_LIMIT_EXCEEDED',
  },

  // Email & Notifications
  EMAIL: {
    QUEUED: 'EMAIL.QUEUED',
    SENT: 'EMAIL.SENT',
    FAILED: 'EMAIL.FAILED',
    BOUNCED: 'EMAIL.BOUNCED',
    RETRY: 'EMAIL.RETRY',
  },

  // Background Jobs
  JOB: {
    QUEUED: 'JOB.QUEUED',
    STARTED: 'JOB.STARTED',
    COMPLETED: 'JOB.COMPLETED',
    FAILED: 'JOB.FAILED',
    RETRYING: 'JOB.RETRYING',
    CANCELLED: 'JOB.CANCELLED',
  },

  // Scheduler / Cron
  SCHEDULER: {
    DISPATCH_STARTED: 'SCHEDULER.DISPATCH_STARTED',
    DISPATCH_COMPLETED: 'SCHEDULER.DISPATCH_COMPLETED',
    MISSED_RUN_DETECTED: 'SCHEDULER.MISSED_RUN_DETECTED',
  },

  // Security & Threats
  SECURITY: {
    UNAUTHORIZED_ACCESS: 'SECURITY.UNAUTHORIZED_ACCESS',
    PERMISSION_DENIED: 'SECURITY.PERMISSION_DENIED',
    INVALID_TOKEN: 'SECURITY.INVALID_TOKEN',
    RATE_LIMIT_EXCEEDED: 'SECURITY.RATE_LIMIT_EXCEEDED',
    BRUTE_FORCE_SUSPECTED: 'SECURITY.BRUTE_FORCE_SUSPECTED',
    SUSPICIOUS_ACTIVITY: 'SECURITY.SUSPICIOUS_ACTIVITY',
  },

  // Database & Cache Infrastructure
  DATABASE: {
    QUERY_SLOW: 'DATABASE.QUERY_SLOW',
    CONNECTION_ERROR: 'DATABASE.CONNECTION_ERROR',
    POOL_EXHAUSTION: 'DATABASE.POOL_EXHAUSTION',
  },

  // System Lifecycle
  SYSTEM: {
    STARTUP: 'SYSTEM.STARTUP',
    SHUTDOWN: 'SYSTEM.SHUTDOWN',
    MAINTENANCE_MODE_TOGGLED: 'SYSTEM.MAINTENANCE_MODE_TOGGLED',
    HEALTH_CHECK: 'SYSTEM.HEALTH_CHECK',
  },
} as const;

export type EventTaxonomyType = typeof EventTaxonomy;
