// apps/worker/src/lib/observability/events.ts
// Worker Event Taxonomy Constants

export const EventTaxonomy = {
  JOB: {
    QUEUED: 'JOB.QUEUED',
    STARTED: 'JOB.STARTED',
    COMPLETED: 'JOB.COMPLETED',
    FAILED: 'JOB.FAILED',
    RETRYING: 'JOB.RETRYING',
  },
  REPORT: {
    GENERATION_STARTED: 'REPORT.GENERATION_STARTED',
    GENERATED: 'REPORT.GENERATED',
    GENERATION_FAILED: 'REPORT.GENERATION_FAILED',
  },
  AI: {
    REQUEST_STARTED: 'AI.REQUEST_STARTED',
    REQUEST_COMPLETED: 'AI.REQUEST_COMPLETED',
    REQUEST_FAILED: 'AI.REQUEST_FAILED',
    FALLBACK_TRIGGERED: 'AI.FALLBACK_TRIGGERED',
  },
  GITHUB: {
    SYNC_STARTED: 'GITHUB.SYNC_STARTED',
    SYNC_COMPLETED: 'GITHUB.SYNC_COMPLETED',
    SYNC_FAILED: 'GITHUB.SYNC_FAILED',
    RATE_LIMIT_EXCEEDED: 'GITHUB.RATE_LIMIT_EXCEEDED',
  },
  EMAIL: {
    QUEUED: 'EMAIL.QUEUED',
    SENT: 'EMAIL.SENT',
    FAILED: 'EMAIL.FAILED',
  },
  SCHEDULER: {
    DISPATCH_STARTED: 'SCHEDULER.DISPATCH_STARTED',
    DISPATCH_COMPLETED: 'SCHEDULER.DISPATCH_COMPLETED',
  },
} as const;
